# Generated by Django 4.2.10 on 2024-06-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='items',
            field=models.ManyToManyField(related_name='suppliers', to='supplier_inventory.item'),
        ),
    ]
